import Head from 'next/head';
import styled from 'styled-components';
import Sidebar from '../components/Sidebar/Sidebar';
import Chat from '../components/Chat';
import { useSession } from 'next-auth/react';
import { db } from '../firebase';
import { collection, onSnapshot, query, orderBy } from 'firebase/firestore';
import { useEffect, useState } from 'react';
import Header from '../components/Header';
import Signin from './signin';
import { getProviders } from 'next-auth/react';

export default function Home({ providers }) {
	const { data: session } = useSession();
	const [orgs, setOrgs] = useState([]);

	useEffect(() => {
		onSnapshot(
			query(collection(db, 'organizations'), orderBy('created', 'asc')),
			(org) => {
				setOrgs(org.docs);
			}
		);
	}, []);

	return (
		<>
			{session ? (
				<>
					<Header />
					<AppBody>
						<Head>
							<title>Slack</title>
							<meta
								name='description'
								content='Generated by create next app'
							/>
							<link rel='icon' href='/favicon.ico' />
						</Head>
						<Sidebar />
						<Chat />
					</AppBody>
				</>
			) : (
				<Signin providers={providers} />
			)}
		</>
	);
}

const AppBody = styled.div`
	display: grid;
	grid-template-rows: auto;
	overflow: hidden;
	position: relative;
	grid-template-columns: 260px auto;
	height: 100vh;
`;

export async function getServerSideProps() {
	const providers = await getProviders();

	return {
		props: {
			providers,
		},
	};
}
